// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: proto/graph.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreFollowRequest is the request for StoreFollow
type StoreFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follower      string                 `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	Followed      string                 `protobuf:"bytes,2,opt,name=followed,proto3" json:"followed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFollowRequest) Reset() {
	*x = StoreFollowRequest{}
	mi := &file_proto_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFollowRequest) ProtoMessage() {}

func (x *StoreFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFollowRequest.ProtoReflect.Descriptor instead.
func (*StoreFollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{0}
}

func (x *StoreFollowRequest) GetFollower() string {
	if x != nil {
		return x.Follower
	}
	return ""
}

func (x *StoreFollowRequest) GetFollowed() string {
	if x != nil {
		return x.Followed
	}
	return ""
}

// StoreFollowResponse is the response for StoreFollow
type StoreFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFollowResponse) Reset() {
	*x = StoreFollowResponse{}
	mi := &file_proto_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFollowResponse) ProtoMessage() {}

func (x *StoreFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFollowResponse.ProtoReflect.Descriptor instead.
func (*StoreFollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{1}
}

func (x *StoreFollowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetFollowingRequest is the request for GetFollowing
type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_proto_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowingRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

// GetFollowingResponse is the response for GetFollowing
type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkeys       []string               `protobuf:"bytes,1,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_proto_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{3}
}

func (x *GetFollowingResponse) GetPubkeys() []string {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

// GetFollowersRequest is the request for GetFollowers
type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_proto_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{4}
}

func (x *GetFollowersRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

// GetFollowersResponse is the response for GetFollowers
type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkeys       []string               `protobuf:"bytes,1,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_proto_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{5}
}

func (x *GetFollowersResponse) GetPubkeys() []string {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

// ResetRequest is the request for Reset
type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{6}
}

// ResetResponse is the response for Reset
type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_proto_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{7}
}

func (x *ResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PingRequest is the request for Ping
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{8}
}

// PingResponse is the response for Ping
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_graph_proto protoreflect.FileDescriptor

const file_proto_graph_proto_rawDesc = "" +
	"\n" +
	"\x11proto/graph.proto\x12\x05graph\"L\n" +
	"\x12StoreFollowRequest\x12\x1a\n" +
	"\bfollower\x18\x01 \x01(\tR\bfollower\x12\x1a\n" +
	"\bfollowed\x18\x02 \x01(\tR\bfollowed\"/\n" +
	"\x13StoreFollowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x13GetFollowingRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\"0\n" +
	"\x14GetFollowingResponse\x12\x18\n" +
	"\apubkeys\x18\x01 \x03(\tR\apubkeys\"-\n" +
	"\x13GetFollowersRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\"0\n" +
	"\x14GetFollowersResponse\x12\x18\n" +
	"\apubkeys\x18\x01 \x03(\tR\apubkeys\"\x0e\n" +
	"\fResetRequest\")\n" +
	"\rResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcb\x02\n" +
	"\fGraphService\x12D\n" +
	"\vStoreFollow\x12\x19.graph.StoreFollowRequest\x1a\x1a.graph.StoreFollowResponse\x12G\n" +
	"\fGetFollowing\x12\x1a.graph.GetFollowingRequest\x1a\x1b.graph.GetFollowingResponse\x12G\n" +
	"\fGetFollowers\x12\x1a.graph.GetFollowersRequest\x1a\x1b.graph.GetFollowersResponse\x122\n" +
	"\x05Reset\x12\x13.graph.ResetRequest\x1a\x14.graph.ResetResponse\x12/\n" +
	"\x04Ping\x12\x12.graph.PingRequest\x1a\x13.graph.PingResponseB\x1aZ\x18nostr-follow-graph/protob\x06proto3"

var (
	file_proto_graph_proto_rawDescOnce sync.Once
	file_proto_graph_proto_rawDescData []byte
)

func file_proto_graph_proto_rawDescGZIP() []byte {
	file_proto_graph_proto_rawDescOnce.Do(func() {
		file_proto_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_graph_proto_rawDesc), len(file_proto_graph_proto_rawDesc)))
	})
	return file_proto_graph_proto_rawDescData
}

var file_proto_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_graph_proto_goTypes = []any{
	(*StoreFollowRequest)(nil),   // 0: graph.StoreFollowRequest
	(*StoreFollowResponse)(nil),  // 1: graph.StoreFollowResponse
	(*GetFollowingRequest)(nil),  // 2: graph.GetFollowingRequest
	(*GetFollowingResponse)(nil), // 3: graph.GetFollowingResponse
	(*GetFollowersRequest)(nil),  // 4: graph.GetFollowersRequest
	(*GetFollowersResponse)(nil), // 5: graph.GetFollowersResponse
	(*ResetRequest)(nil),         // 6: graph.ResetRequest
	(*ResetResponse)(nil),        // 7: graph.ResetResponse
	(*PingRequest)(nil),          // 8: graph.PingRequest
	(*PingResponse)(nil),         // 9: graph.PingResponse
}
var file_proto_graph_proto_depIdxs = []int32{
	0, // 0: graph.GraphService.StoreFollow:input_type -> graph.StoreFollowRequest
	2, // 1: graph.GraphService.GetFollowing:input_type -> graph.GetFollowingRequest
	4, // 2: graph.GraphService.GetFollowers:input_type -> graph.GetFollowersRequest
	6, // 3: graph.GraphService.Reset:input_type -> graph.ResetRequest
	8, // 4: graph.GraphService.Ping:input_type -> graph.PingRequest
	1, // 5: graph.GraphService.StoreFollow:output_type -> graph.StoreFollowResponse
	3, // 6: graph.GraphService.GetFollowing:output_type -> graph.GetFollowingResponse
	5, // 7: graph.GraphService.GetFollowers:output_type -> graph.GetFollowersResponse
	7, // 8: graph.GraphService.Reset:output_type -> graph.ResetResponse
	9, // 9: graph.GraphService.Ping:output_type -> graph.PingResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_graph_proto_init() }
func file_proto_graph_proto_init() {
	if File_proto_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_graph_proto_rawDesc), len(file_proto_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_graph_proto_goTypes,
		DependencyIndexes: file_proto_graph_proto_depIdxs,
		MessageInfos:      file_proto_graph_proto_msgTypes,
	}.Build()
	File_proto_graph_proto = out.File
	file_proto_graph_proto_goTypes = nil
	file_proto_graph_proto_depIdxs = nil
}
